version: "3"

services:
  db:
    image: postgres:9.5
    restart: always
    env_file:
      - database.env
    ports:
      - "5432:5432"

  app-rotator:
    build:
      context: ..
    command: ["./wait-for-postgres.sh", "db", "./bin/rotator"]
    ports:
      - 8086:8086
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - DB_HOST=db

  migration:
    build:
      context: ..
      dockerfile: migrations/Dockerfile
    command: ["./wait-for-postgres.sh", "./entrypoint.sh"]
    depends_on:
      - db
    env_file:
      - database.env
    environment:
      - POSTGRES_HOST=db